use magnus::{Module, Object, method};

const PRESETS: [&str; 113] = [
    "generic",
    "paddedcell",
    "room",
    "bathroom",
    "livingroom",
    "stoneroom",
    "auditorium",
    "concerthall",
    "cave",
    "arena",
    "hangar",
    "carpetedhallway",
    "hallway",
    "stonecorridor",
    "alley",
    "forest",
    "city",
    "mountains",
    "quarry",
    "plain",
    "parkinglot",
    "sewerpipe",
    "underwater",
    "drugged",
    "dizzy",
    "psychotic",
    "castle_smallroom",
    "castle_shortpassage",
    "castle_mediumroom",
    "castle_largeroom",
    "castle_longpassage",
    "castle_hall",
    "castle_cupboard",
    "castle_courtyard",
    "castle_alcove",
    "factory_smallroom",
    "factory_shortpassage",
    "factory_mediumroom",
    "factory_largeroom",
    "factory_longpassage",
    "factory_hall",
    "factory_cupboard",
    "factory_courtyard",
    "factory_alcove",
    "icepalace_smallroom",
    "icepalace_shortpassage",
    "icepalace_mediumroom",
    "icepalace_largeroom",
    "icepalace_longpassage",
    "icepalace_hall",
    "icepalace_cupboard",
    "icepalace_courtyard",
    "icepalace_alcove",
    "spacestation_smallroom",
    "spacestation_shortpassage",
    "spacestation_mediumroom",
    "spacestation_largeroom",
    "spacestation_longpassage",
    "spacestation_hall",
    "spacestation_cupboard",
    "spacestation_alcove",
    "wooden_smallroom",
    "wooden_shortpassage",
    "wooden_mediumroom",
    "wooden_largeroom",
    "wooden_longpassage",
    "wooden_hall",
    "wooden_cupboard",
    "wooden_courtyard",
    "wooden_alcove",
    "sport_emptystadium",
    "sport_squashcourt",
    "sport_smallswimmingpool",
    "sport_largeswimmingpool",
    "sport_gymnasium",
    "sport_fullstadium",
    "sport_stadiumtannoy",
    "prefab_workshop",
    "prefab_schoolroom",
    "prefab_practiseroom",
    "prefab_outhouse",
    "prefab_caravan",
    "dome_tomb",
    "pipe_small",
    "dome_saintpauls",
    "pipe_longthin",
    "pipe_large",
    "pipe_resonant",
    "outdoors_backyard",
    "outdoors_rollingplains",
    "outdoors_deepcanyon",
    "outdoors_creek",
    "outdoors_valley",
    "mood_heaven",
    "mood_hell",
    "mood_memory",
    "driving_commentator",
    "driving_pitgarage",
    "driving_incar_racer",
    "driving_incar_sports",
    "driving_incar_luxury",
    "driving_fullgrandstand",
    "driving_emptygrandstand",
    "driving_tunnel",
    "city_streets",
    "city_subway",
    "city_museum",
    "city_library",
    "city_underpass",
    "city_abandoned",
    "dustyroom",
    "chapel",
    "smallwaterroom",
];

fn preset_fn(this: magnus::Value) {}

pub fn bind(ruby: &magnus::Ruby) -> Result<(), magnus::Error> {
    let module = ruby.define_module("ALEffect")?;

    let class = module.define_class("EAXReverb", ruby.class_object())?;
    for preset in PRESETS {
        class.define_method(format!("load_preset_{preset}"), method!(preset_fn, 0))?;
    }

    Ok(())
}
