name: Autobuild

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install libraries
        run: |
          sudo apt update
          sudo apt install libgtk-3-dev libatk1.0-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev libasound2-dev libudev-dev clang mold -y
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      # TODO cache ruby too
      - name: Build ruby
        run: |
          cd ${{ github.workspace }}/ruby
          ./build-ruby.sh
      - name: Build sapphire
        run: cargo build
      - name: Setup artifact
        run: |
          mkdir -p ${{ github.workspace }}/artifact
          cp ${{ github.workspace }}/target/debug/sapphire ${{ github.workspace }}/artifact
          cp ${{ github.workspace }}/ruby/pfx/libruby.* artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sapphire-linux
          path: ${{ github.workspace }}/artifact/
